### ISSUE TITLE
[FR] document behavior of undefined, internal (none) and self referencing triggers

### ISSUE THREAD

**Issue by erkr** [edalquist/ha_state_machine#5]
I have my first state machine running. I noticed a warning is logged when a trigger if fired in a state that doesn't handle that trigger ( no transition defined for that trigger):

```text
This error originated from a custom integration.

Logger: transitions.core
Source: custom_components/state_machine/sensor.py:188
Integration: State Machine
First occurred: 23:29:39 (1 occurrences)
Last logged: 23:29:39

Can't trigger event low from state HEATING!
```

That can be totally legit. For example, triggers that should not reset the timeout in a particular state. So I propose adding an option in the state machine settings (checkbox) to ignore triggers in states that don't handle them. 

Alternative is to explicitly ignore triggers, with a keyword.  So in the example below, the low and off triggers don't reset the timeout in the state ANTIWRINKLE. E.g.:

```
    "VENTING": {
      "high": "HEATING",
      "middle": "VENTING",
      "low": "ANTIWRINKLE",
      "off": "IDLE"
    },
    "ANTIWRINKLE": {
      "timeout": { "after": 300, "to": "IDLE" },
      "high": "HEATING",
      "middle": "VENTING",
      "low":  "_ignore_trigger_",
      "off":  "_ignore_trigger_"
    }
```

Best Eric

**Comment by erkr** [comment]
Thanks! I'm looking forward for a solution. 
My work around is to filter the triggers in the automation part. But that is ugly as it as scatters the state machines knowledge between the state sensor and the automation part:
```yaml

          - condition: template
            alias: FSM Event
            value_template: |
              {{trigger.id.startswith('FSM:')}}
          - condition: template
            alias: FSM Event
            value_template: |
              {{trigger.id != 'FSM:on' or
                states('sensor.dryer_state') == 'IDLE' or
                states('sensor.dryer_state') == 'A-WRINKLE' }}
```

Ps: I looked a little into the transition library and saw the destination can be set "none". Not tried yet if that works
